name: Terraform tflint
description: Runs a Terraform tflint checks

inputs:
  tflint-version:
    required: false
    default: 'v0.52.0'
  tflint-config-file:
    required: false
    default: '.tflint.hcl'
  tflint-config:
    required: false
    default: ''

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: ${{ inputs.tflint-version }}
      - name: Show version
        shell: bash
        run: tflint --version

      - name: Init TFLint
        shell: bash
        run: |
          TFLINT_CONFIG_FILE="${{ inputs.tflint-config-file }}"
          if [ ! -f "${TFLINT_CONFIG_FILE}" ]; then
            if [ -n "${{ inputs.tflint-config }}" ]; then TFLINT_CONFIG="${{ inputs.tflint-config }}"; fi
            echo -e "${TFLINT_CONFIG}" > "${TFLINT_CONFIG_FILE}"
          fi
          tflint --init --config=${TFLINT_CONFIG_FILE}
        env:
          TFLINT_CONFIG: |
            config {
              format = "checkstyle"
            }
            
            plugin "terraform" {
              enabled = true
              preset  = "recommended"
            }
            
            plugin "aws" {
              enabled = true
              version = "0.37.0"
              source  = "github.com/terraform-linters/tflint-ruleset-aws"
            }

      - name: Run TFLint
        shell: bash
        run: |
          tflint --recursive --config=${TFLINT_CONFIG_FILE}
